# Server Port
server.port=8080

# Razorpay Credentials
razorpay.key.id=rzp_live_ThV1DZFZJlCYuF
razorpay.key.secret=oGk7T0yoJwG7PT8JS3GamfsB

# Google Sheets ID
1jbLLUct1Zi2u10iReltIzaAForbXeopkGrynztN-Ep8